version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3500:3500"
    volumes:
      - .:/app
    links:
      - postgres
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes_from:
      - postgres_data
    environment:
      PGDATA : /var/lib/postgresql/data/pgdata
    links:
      - postgres_data
  postgres_data:
    image: postgres:9.4
    command: /bin/true
